- name: run playbook
  hosts: all
  tasks:
  - name: install package
    apt:
     name: apache2
     state: present 
  - name: create file
    copy:
     content: "Welcome to Server"
     dest: /var/www/html/index.html
  - name: restart service
    service:
      name: apache2
      state: restarted
      enabled: true
  - name: create user
    user:
     name: gaurav
     state: present
    